//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class assigned_test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assigned_test()
        {
            this.test_result = new HashSet<test_result>();
        }
    
        public int id { get; set; }
        public Nullable<int> test_id { get; set; }
        public Nullable<int> assigned_by { get; set; }
        public Nullable<int> assigned_to { get; set; }
        public int attempts_allowed { get; set; }
        public Nullable<System.DateTime> assigned_at { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual test test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_result> test_result { get; set; }
    }
}
