//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class correct_answer
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> correct_option_id { get; set; }
    
        public virtual answer_option answer_option { get; set; }
        public virtual question question { get; set; }
    }
}
