//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_subject
    {
        public int id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> subject_id { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual user user { get; set; }
    }
}
